services:

  auth:
    image: node:22
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 3000:3000
    command: bash -c "yarn && yarn start:dev auth"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_DEFAULT_BUCKETS: "ecommerce"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: