services:

  postgres:
    image: postgres:latest
    container_name: "live.ecommerce"
    volumes:
      - pgdata_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"

  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_PORT: 27017
      MONGO_REPLICA_HOST: localhost
      MONGO_COMMAND: 'mongosh'
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data

volumes:
  pgdata_data:
  mongo-data: